version: "3.1"

services:
  apache:
    build: ./
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    links:
      - mysql:mysql
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./databases:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
